### PR TITLE
Resolve DTD Violations in Sample-Article

### PR DESCRIPTION
**Pull request by Jahrme**
Adjust the Sample-Article and DTD resulting in fewer DTD violations in the Sample-Article.

### CODE REVIEW

**Comment by davidfarmer** [comment]
I think it is more typical to put the statement of a definition before the notation.
So I suggest reverting the changes around line 290.

**Comment by rbeezer** [comment]
Thanks, Jahrme.  `%markup` should be contained within `%linear` so one edit in the DTD looks duplicative.  I'll experiment/fix when I merge, so don't worry about it.

Thanks for doing this, KDC will be pleased. ;-)  The remainder "need work" so are not worth fixing now.

**Comment by rbeezer** [comment]
@davidfarmer - the `notation` will not be displayed at all here - placement is for "List of Notation" to function.  It is "metadata" of sorts, very similar to `index`.

I want all this stuff up top, so I can relax the necessity of `statement` predictably.

**Comment by davidfarmer** [comment]
Since many people use the sample article to figure out what to do,
I didn't want it to give the impression that notation should come first.

Eventually we want to develop an MBX style guide, and that will
likely have notation after statement.

**Comment by rbeezer** [comment]
"notation" will not be visible to the reader there.

It is information about the "definition", like its "title".  It is (a) a target 
for the cross-reference from the "List of Notation", (b) content for the "List 
of Notation".

It needs to handled specially, and typically drops a target - we want that 
target at the top of the "definition" in practice (eg PDF).

To put it at the end (a) is contrary to practice with "title", "caption" and 
"index", (b) unnecessarily complicated for implementation.

IF we make a new "block" titled "Notation", then I agree that the right 
presentation is after the definition (and so should be authored there), and we 
can talk about other places where it might appear.

Rob

**Comment by rbeezer** [comment]
Thanks, Jahrme.  Lists are going to change (must lice in `list` or `p`) so I reversed a few things.  DTD **will** catch up soon.  At  770dd766  but forgot to put PR number in commit message, so it won't magically appear here.  Has your name on it anyway.

**Pull request closed without merging**
