### PR TITLE
WeBWorK Issues 2

### PR DESCRIPTION
**Pull request by Alex-Jordan**
More coming. First commit from #437 cherry-picked and amended to make the occurrences report mimic the deprecation report style.

### CODE REVIEW

**Comment by Alex-Jordan** [comment]
Now caught up to #437, but with feedback addressed.

**Comment by Alex-Jordan** [comment]
582832e:

- moves inclusion of `mathbook-webwork-pg` in `mathbook-html` to the end of the file, addressing #401 and a few other issues that hadn't been discovered yet. Following items are related to get common, html, and webwork-pg all playing nicely with each other.
- where appropriate, specifies templates in `mathbook-webwork-pg` to begin with `webwork//`
- renames a few called templates in `mathbook-webwork-pg` so they do not conflict/overwrite templates elsewhere in MBX that only coincidentally have the same name
- deleted extra templates for nbsp, ndash, and mdash. Their presence seemed unnecessary and in fact I noticed an nbsp that was not processed correctly prior to removal, but processed correctly after removal.

To test this breaks nothing, I compiled the sample-article under dev branch, and then with this branch including this commit. Stored in separate folders. Used diff (not git diff) to compare. Sample-article output was identical except for different time stamps. Including all knowls.

Did the same with webwork sample-chapter. html output was identical. knowl outputted differed where expected: list items and base64 strings for webwork problems.

**Comment by Alex-Jordan** [comment]
OK, stopping for now. Original three commits (with revisions) and now three more commits.

Several items remain on my local branch from recent surge
- Some trivial/cosmetic corrections
- Some big ones that need to wait until the WeBWorK PR is approved (addressing #399 and more)

**Comment by rbeezer** [comment]
b827ab2: very cute.  ;-)

Thanks very much for all the clean-up!  Merged as-is with a couple of `WeBWorK` inserted into commit messages.  Very pleased to get that priority business straightened out.

**Pull request closed without merging**
