### PR TITLE
add <sidebyside> example with single child

### PR DESCRIPTION
**Pull request by sklarjk**
Added after subsection "Common Side-By-Side Constructions."

### CODE REVIEW

**Comment by rbeezer** [comment]
Thanks!  I added a dumb paragraph between the two, so it was clear they were not a `sbsgroup`.  All credit is still yours - I just smashed the small additional change into your commit.

You know how to clean-up now on our end.

**Comment by sklarjk** [comment]
Yay, glad I'm good for more than just making people nonplussed by my ugly
hacks and myself nonplussed by Git.

Sorry I forgot to include the #670.

On Aug 10, 2017 3:51 PM, "Rob Beezer" <notifications@github.com> wrote:

Thanks! I added a dumb paragraph between the two, so it was clear they were
not a sbsgroup. All credit is still yours - I just smashed the small
additional change into your commit.

You know how to clean-up now on our end.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/rbeezer/mathbook/pull/670#issuecomment-321694543>, or mute
the thread

**Comment by rbeezer** [comment]
On 08/10/2017 03:57 PM, Jessica K. Sklar wrote:
> Sorry I forgot to include the #670.

*That's* OK.  You have to apologize for not capitalizing the commit message.  ;-)

**Comment by sklarjk** [comment]
Doh!

**Pull request closed without merging**
