### PR TITLE
Add Asymptote links to HTML

### PR DESCRIPTION
**Pull request by sean-fitzpatrick**
This places a link below each Asymptote figure, inviting the user to click to view a full size image.

Doesn't differentiate between 2D and 3D Asymptote, but primarily useful for 3D, where rotating a figure sometimes results in it getting clipped by the bounding box.

It is controlled by the same publisher variable as Asymptote links in PDF. (Should that variable move from PDF to common?)

### CODE REVIEW

**Comment by rbeezer** [comment]
Do you see all those merge commits?  And a bunch of old Asy work?

Did you start this on some old existing branch?  Is the actual content just in ad7c7b9d61d2c8d266ba9c49a195c6d5e5b1f24e

**Comment by sean-fitzpatrick** [comment]
I started off of a new branch, but on my own fork of `dev`. So my regular `git pull` has been a regular `git fetch upstream` `git merge upstream/dev`.

Maybe a better way to keep in sync with upstream, but it's the one I learned!

Alternative for a cleaner pull request is to delete my fork, refork, branch, and commit. (Which I can do.)
But yes it's just the last commit.

**Comment by sean-fitzpatrick** [comment]
I must have made a commit to the dev branch at some point in the past because it should just be doing a fast forward for the merge

**Comment by mitchkeller** [comment]
I’ve learned that the workflow that aligns best with how @rbeezer reviews these sorts of things is to make a branch `mywork` (or whatever) cleanly off `dev`. Always do `git pull upstream dev` on your local copy of `dev`. Then `git switch mywork` (or `git checkout mywork`) and `git rebase dev`. This allows you to avoid all of the messy merge commits. The rebase also gives a decent way to correct any of your working code that gets impacted by changes on `upstream/dev` while you’ve been working.

**Comment by sean-fitzpatrick** [comment]
Yeah, I think what happened is I made a commit on `dev` at some point by mistake.
So basically if you forget to make a new branch even once you might as well delete the fork and try again :-)

**Comment by mitchkeller** [comment]
I didn’t have to go so far as deleting my fork. I do have a branch called `rbeezer-dev` that is set up to track `rbeezer/dev`, and I do `git pull upstream dev` into that branch and then rebase on `rbeezer-dev`. I was actually thinking today that I should go ahead and see how much hassle it would be (at least locally) to rename that branch to `dev`. No one should be looking at my `dev` or `rbeezer-dev` branch on GitHub anyway, as if there’s something worth seeing on my fork, it’s going to be on another branch that I either want them to test something on or that I’ve made a PR from.

**Comment by sean-fitzpatrick** [comment]
Closing to try again with a cleaner commit.

**Pull request closed without merging**
