### PR TITLE
Unstructured

### PR DESCRIPTION
**Pull request by Alex-Jordan**
This is not to be merged. I am checking in to ask for an inspection that so far, so good. See #1664.

### CODE REVIEW

**Comment by rbeezer** [comment]
Looking good.  Do you get any changes (perhaps just for `worksheet` since I've made an exception for a division full of them)?

Filters will be useful.  I think "appendix" belongs in "traditional" and "solutions" belongs in "specialized".  But I don't think `match="*[<filter>]"` is best, instead it should just be a list of the elements - so perhaps there should be lists as entities, too.  I know there would be other places I might use them if they existed.

**Comment by Alex-Jordan** [comment]
No changes in output with what is here so far.

I tried a list of the elements first, but couldn't get the match priority to behave. At one point I had `match="*"` with the error, then `match="&TRADITIONAL-DIVISION;"` and then the other one, but `match="*"` was winning the precedence every time. But I could try harder to make that work.

Do you have a preference between three different templates, versus one that uses a `xsl:choose`?

**Comment by Alex-Jordan** [comment]
At the moment I have it as:

```
<xsl:template match="*" mode="is-traditional-division">
    <xsl:choose>
        <xsl:when test="self::*[&TRADITIONAL-DIVISION-FILTER;]">
            <xsl:value-of select="true()"/>
        </xsl:when>
        <xsl:when test="self::*[&SPECIALIZED-DIVISION-FILTER;]">
            <xsl:value-of select="false()"/>
        </xsl:when>
        <xsl:otherwise>
            <xsl:message>PTX:BUG: asking if a non-division (<xsl:value-of select="local-name(.)"/>) is a traditional division</xsl:message>
        </xsl:otherwise>
    </xsl:choose>
</xsl:template>
```

Any red flags there? Or opportunities to simplify?

**Comment by rbeezer** [comment]
I think self::*[ ] is redundant.  Just set the test= to the entity?

**Comment by Alex-Jordan** [comment]
OK, ready for review. I cannot come up with a good way to remove the "un". So I've just replaced all those instances with a logical combination of two more basic templates. So like:
```
<xsl:when test="$is-specialized-division-in-unstructured = 'true'">
```
becomes

```
<xsl:when test="$is-specialized-division = 'true' and $is-child-of-structured = 'false'">
```

**Comment by rbeezer** [comment]
Very good!  Thanks for chasing through this one.  Yes, much more verbose, but it is complicated and I think this makes it clearer when the code needs maintenance.

Exploded one commit into three, with you as author, fixing one typo along the way.  Used a merge commit to label the branch of four commits with the GH PR number.  So basically zero change to the code.

Thanks again.  I'll be using parts of this in the next few minutes.  ;-)

**Pull request closed without merging**
