### PR TITLE
Add support for linking asymptote figures in PDF to interactive HTML counterparts

### PR DESCRIPTION
**Pull request by sean-fitzpatrick**
Adds publisher variables for `baseurl` (set baseurl) and `asy-links` (yes/no for adding links).

Tested following scenarios:

- baseurl set and `links="yes"` : adds href pointing to html version for all asymptote images
- `links="no"` : no href added to asymptote images
- some value other than yes or no used for `@links`: warning message issued, and defaults to `no`
- no value given for `@links`: defaults to `no`
- `@links` set to `yes` but no baseurl given: warning message issued that a baseurl is needed. href still gets added to each image, but now points to `/images/asy-fig.pdf` instead of `baseurl/images/asy-fig.pdf`, so it does nothing.

No documentation (yet).

### CODE REVIEW

**Comment by sean-fitzpatrick** [comment]
Ah, shoot -- I didn't account for the change you made to the author guide for the previous asymptote commit.

**Comment by sean-fitzpatrick** [comment]
One thing you will probably want me to change: I wasn't sure if it was allowed to declare the `$baseurl` variable in both `pretext-common` (the original location, referencing `docinfo/html`) and also in the publisher variables, so I commented it out in `pretext-common`.

**Comment by rbeezer** [comment]
> Ah, shoot -- I didn't account for the change you made to the author guide for the previous asymptote commit.

Welcome to my world.  You can always do a forced push on a PR like this.  Not sure if that applies here.

I'll look later today, deep into "managed" images for EPUB and ODT.

**Comment by rbeezer** [comment]
Having trouble getting my full attention on this one.

Bulk of this looks great, but I'll likely squash the whole thing and make a few edits.  Publisher file section might be `latex`, not `pdf`, of two minds on that one.

Commenting-out bits of `pretext-common.xsl` is defintely discouraged!  ;-)  I know what to do.  And some more whitespace correction, since you must have touched the Topics chapter of the Guide.  (Are you able to control not committing these?  They are my fault, and they do need fixing, but complicate accepting PRs).

I'll try to get serious about this during the weekend.  Please leave as-is, no real problems on my end, I think.

**Comment by rbeezer** [comment]
For a "print" PDF, it'd be best if this was turned off.  Probably not a big deal, but I'd like print to be print, no hyperlinking, etc., lurking about to muck up an upload to a print-on-demand site.

Then, if a base URL is defined, an "electronic" PDF **should** turn this on.

Which means that `latex.print` should become a publisher variable, too.  And maybe a few more while I'm at it.  So I think I'll go down that road first, and soon, so I'll let this wait its turn.

**Comment by sean-fitzpatrick** [comment]
That sounds good to me.
I think the phantom change to the guide is because I started this branch before the other Asymptote pull request for merged, and then there was a merge conflict on the changes there (due to me doing some wrong git things).

My current solution for the different options for LaTeX is to have several different stylesheets.
In addition to tcolorbox styling I set all the string parameters I need in there.

**Comment by rbeezer** [comment]
> I started this branch before the other Asymptote pull request for merged, and then there was a merge conflict on the changes there (due to me doing some wrong git things).

Well, that was a mess.  ;-)  Under control now.  Have a few items switched over to the publisher file and now mid-way though this PR.  Probably pick it back up some other evening soon.

**Comment by rbeezer** [comment]
Done, merged, pushed, and documented.  Whew.  Your name is on the primary commit, though it may look a bit different.

Look at how the `asymptote-links` variable is formed.  Marginally cleaner.  Thanks for suggesting this one and the running start.

**Comment by sean-fitzpatrick** [comment]
Glad to be of help! (And to get what I think will be a useful feature. One more step towards an official APEX in PreTeXt.)

**Pull request closed without merging**
