### PR TITLE
Author's Guide: WeBWorK chapter

### PR DESCRIPTION
**Pull request by Alex-Jordan**
WeBWorK chapter for author guide. Two subsections that are "planned". Also, my next project will be to remove the answer tag from webwork tags, putting var to that purpose by way of a form attribute. Documentation will change at that time.

### CODE REVIEW

**Comment by Alex-Jordan** [comment]
To whatever degree it's possible, this pull request now has some urgency. (Urgency is always relative, of course). pg archiving and latex output are currently broken. (pg archiving is recognizing empty webworks when it shouldn't be, and mathbook-latex.xsl never had elements/element replaced with set/member). 

I have fixed these things on the branch where I am removing answer and replacing it with var[form], but I can't submit that for a pull request until this one is pulled into dev. The reason is that the last thing to do is to update the chapter in this pull request to reflect how answer blanks are written now.

**Comment by rbeezer** [comment]
OK, received.  I've cleared out a few other quick things and will try to make 
progress on pull requests ASAP.  Busy with graduation weekend at the moment.

Aah, those nasty empty webwork.  Gave me no end of trouble.  See where/how I 
dealt with them elsewhere.  Sorry about missing that, and missing the set/member 
in LaTeX (not sure how I blew that one).

Rob

**Comment by rbeezer** [comment]
Had time for a first pass visually - looks good.  I'll try to ge this merged today sometime (and have my script do updates of the live version).

**Comment by Alex-Jordan** [comment]
Cool. Found another issue: mathbook-latex.xsl never changed @format to
@form. Also being fixed in my other branch. I'll do my best to commit
things in an organized way; I may be able to separate the fixes from the
answer->var changes. Or I may not, since sometimes the issues are tied
together.

This all speaks well for doing thorough testing before pushing out to the
world. I only caught these things while checking that answer->var was
working as intended. I know you are usually thorough, but I confess to
sometimes saying to myself "it's probably fine; how could it not be?"
without actually checking. A good lesson for me to check things.

On Sat, May 14, 2016 at 1:29 PM, Rob Beezer <notifications@github.com>
wrote:

> Had time for a first pass visually - looks good. I'll try to ge this
> merged today sometime (and have my script do updates of the live version).
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/rbeezer/mathbook/pull/264#issuecomment-219249958>
>



-- 
Alex Jordan
Mathematics Instructor
Portland Community College

**Comment by Alex-Jordan** [comment]
I'm going to get fancy and try http://stackoverflow.com/questions/1085162/commit-only-part-of-a-file-in-git to commit just parts of files to see if I can separate these fixes.

**Comment by Alex-Jordan** [comment]
I'm veering off thread since I'm talking about a branch I have that is not this branch up for a pull request, but this still seems like the best place to post this question for you (Rob). It's all related to the earlier posts in this thread.

I staged only the bits of my edits to `mathbook-latex.xsl` that correspond to the `set/member` issue. I can commit them, but I'd like guidance on a good commit message. There is a commit from April 12:

```
commit ffa5824af3c263fc27b9a6d56a3bf5e2c63516e3
Author: Rob Beezer <beezer@ups.edu>
Date:   Tue Apr 12 19:39:34 2016 -0700

    Rename WeBWorK choice answers as set-with-members
```

What would be an OK commit message to complete this in `mathbook-latex.xsl`?

**Comment by rbeezer** [comment]
Yes, `-p` works well - I do this frequently.

Commit message: maybe just copy the previous one, but emphasize you are picking up the LaTeX version

**Comment by rbeezer** [comment]
Excellent!  Thanks very much.  Merged locally and pushed.

**Pull request closed without merging**
