### PR TITLE
Typo?

### PR DESCRIPTION
**Pull request by kcrisman**
I think this is a typo, not 100% sure what is meant.

### CODE REVIEW

**Comment by rbeezer** [comment]
Not a typo.  "Tables" - all of them.  Generically.

**Comment by kcrisman** [comment]
Right, so is it "Table" or "Tables"?  I changed it to "Tables" in this commit.

**Comment by rbeezer** [comment]
My mistake, I think I read the diff backwards - will fix soon.  Thanks.

**Comment by rbeezer** [comment]
Merged, sorry for the confusion.

**Pull request closed without merging**
