### PR TITLE
HTML: scope for table column headers

### PR DESCRIPTION
**Pull request by Alex-Jordan**

### CODE REVIEW

**Comment by rbeezer** [comment]
Should this not also be the case for `@header = 'vertical'`?  In which case, maybe it makes sense to conditon on `$header-row-elt`?

**Comment by Alex-Jordan** [comment]
Maybe I shouldn't write code during the meetings.

**Comment by rbeezer** [comment]
"Can you multitask?"  ;-)

**Comment by Alex-Jordan** [comment]
Is it better now?

**Comment by Alex-Jordan** [comment]
> "Can you multitask?" ;-)

You didn't specify performance :)

**Comment by rbeezer** [comment]
Much better.  ;-)  And if there needs to be another conditional change sometime later, perhaps a boolean variable will be best for readability.  Website update perhaps sometime later today.

**Pull request merged**
