### PR TITLE
Pretext: Allow command-line options in pretext.cfg

### PR DESCRIPTION
**Pull request by jjrsylvestre**
Allow users to specify extra command line options for specified commands in pretext.cfg.

For example, I recently needed to pass the threshold option to pdf-crop-margins, as some images that were cropped fine by old pdfcrop were being more aggressively cropped by new pdf-crop-margins.

(That's the only case I tested this code on, but since all the code edits are essentially the same, it *should* all work fine for the other commands. *fingers-crossed*)

### CODE REVIEW

**Comment by rbeezer** [comment]
A visual scan of the code looks good.  I wasn't sure how you were going to accomplish that -- I like it in the config file.

If there was **any** good documentation, I'd suggest you add to it.  :-(

**Comment by jjrsylvestre** [comment]
OK, added some rudimentary documentation to the stock pretext.cfg itself.

The documentation for configparser says that occurrences of delimiters in values are allowed, and sure enough it works fine. Though to avoid confusion you might consider changing the delimiter in pretext.cfg to : instead of =.

**Comment by rbeezer** [comment]
@jjrsylvestre Sorry - I lost track of this one until you mentioned it a while back.  I have some serious Python work to do soon, so I'm saving this until my head is into that work.  Soon!  I really don't want to forget again!  ;-)

**Comment by rbeezer** [comment]
Thanks, Jeremy.  Merged this just now, even though I think I've made a mess for myself with some other pending work of mine.  ;-)

Why?  You'll see a need on `pretext-support`.  I'm posting there now.  Perhaps you can have a look?

Nice work.  And timely.  Thanks again.

**Comment by rbeezer** [comment]
@jjrsylvestre I think this needed one little fix-up.  You mind taking a peek and make sure I did it right?  Seems to function just fine.  Thanks.

See 14889567d57a9c863b1596166ca9af911a571bed

**Comment by jjrsylvestre** [comment]
Looks good, not sure how I missed that one. Hope it didn't cause extra
traffic on -support.

**Comment by rbeezer** [comment]
Looks like there were other adjustments there, since it was a bit more complicated than the others.

No problem - I hit it while testing some image management work, and got it fixed pretty quickly.  My own personal support list.

Thanks for the quick check!

**Pull request closed without merging**
