### PR TITLE
Author's Guide: Sublime Text section in Editors appendix

### PR DESCRIPTION
**Pull request by daverosoff**
Please let me know if there's any way I can make the pull requests more convenient for you (more/less granular, etc.), or if you'd like me only to submit finished work.

The conflict commit is due to my having started a WSL section and then removing it after I saw there was already one present in a new pull.

### CODE REVIEW

**Comment by rbeezer** [comment]
Dear Dave,

I've been looking forward to this one!  Thanks.

I tend to squash commits together, or maybe rearrange them a bit.  I always try to make sure your name stays on your work (iff).  I have a local procedure that works for me and seems to keep GitHub pretty happy.  So, short answer, almost anything you send me I can deal with, and if not, I'll let you know.

I'll presume a pull request means its ready-to-go and it may be a while before you can do more.  Or leave a message if you just want me to review something in-progress for some reason,

Thanks for the contributions!

**Comment by daverosoff** [comment]
Later this week I plan to post to the group about the MBXTools package.

**Comment by rbeezer** [comment]
Dave,

What is the `MBXTools` package?  ;-)  Looking this PR over now.

Rob

**Comment by rbeezer** [comment]
Never mind.  I'm getting there!

**Comment by rbeezer** [comment]
Dear Dave,

Thanks for the careful job on this excellent contribution (and for work on MBXTools!).  Using `--word-diff` on `git show` will let you easily see the minor edits I made.

* I forgot the PR # on commits - your work is at 008d58c9
* `cd` (code display) is new, for intra-paragraph breaks with verbatim text
* I try to avoid contractions in formal stuff
* `autoname="yes"` is not needed since I do it globally, see below
* For Author's Guide only, `tag`, `tage` and `attribute` tags, see below
* I have `"draw_white_space": "all"` in my Settings, maybe you can include that?

I should create a simple build script, since you need "extra" xsl, etc.  Here are my commands, you can infer what needs to happen:

```
mkdir /tmp/ag
cd /tmp/ag
cp ~/mathbook/mathbook/doc/author-guide/xsl/* ~/mathbook/mathbook/user/
# cp -a ~/mathbook/mathbook/doc/author-guide/images .

HTML
xsltproc --xinclude ~/mathbook/mathbook/user/author-guide-html.xsl ~/mathbook/mathbook/doc/author-guide/author-guide.xml
firefox mathbook-author-guide.html &

LaTeX
xsltproc --xinclude ~/mathbook/mathbook/user/author-guide-latex.xsl ~/mathbook/mathbook/doc/author-guide/author-guide.xml; pdflatex mathbook-author-guide.tex
```

Thanks again!

Rob

**Comment by daverosoff** [comment]
You are welcome, and thanks for the tips. I will try to remember these things (and I have turned on whitespace in MBX mode :)

**Comment by rbeezer** [comment]
Thanks, Dave.  I have a few contributions and bugs backed up, but will get to 
this soon!

**Pull request closed without merging**
