### PR TITLE
Add FontAwesome media control icons

### PR DESCRIPTION
**Pull request by whaynes**
I needed an icon for fast-forward which wasn't available, so I have added the suite of icons for the media control and I updated the corresponding section in the author's guide.

```
<icon name='power'/>
<icon name="media-play" />
<icon name="media-pause" />
<icon name="media-stop" />
<icon name="media-fast-forward" />
<icon name="media-rewind" />
<icon name="media-skip-to-end" />
<icon name="media-skip-to-start" />
```

**Important note**

When I was testing this, Latex reported that FontAwesome was not installed as a system font, which was true.  However when I went to the fontawesome.com and downloaded and installed them I continued to get the same error.  Apparently the issue is that in the latest version 5, the fonts are called **Font Awesome 5 Free-Regular-400.otf** and **Font Awesome 5 Free-Solid-900.otf** but  PreTeXt was looking for the previous version called **FontAwesome.otf**

I was able to scrounge this file from another site, but it doesn't seem to be available on the official FontAwesome site.

### CODE REVIEW

**Comment by rbeezer** [comment]
I've been away for a week, and thought I replied to this (maybe I was not signed in).  Anyway, sorry for the delay.  I'll get to it in a bit.

**Comment by rbeezer** [comment]
Nice work, Will.  Thanks.  _The Guide_ is being rebuilt right now.

**Comment by rbeezer** [comment]
Just a note that there was some git-astrophe here.   The commit of interest is followed by five existing commits on the branch being proposed here.  I was able to isolate the one commit and trash the others, but it was pretty unnatural.  I can't even imagine how this happened.  ;-)

So the best I can do to help is suggest that maybe there is some help here:

https://pretextbook.org/doc/guide/html/section-162.html

Thanks,
Rob

**Comment by rbeezer** [comment]
Oops, forgot to comment on fonts.  I'll make a new issue and try to investigate further. Are you using `pdflatex` or `xelatex`?  It makes a big difference for fonts.

**Comment by whaynes** [comment]
I’m using xelatex.

Sorry for the git error, but glad you could straighten it out.  I’ve read the instructions multiple times, but I still get confused about which branch I’m on, who’s upstream, who’s the master, etc. etc. etc.

Will

**Pull request closed without merging**
