### PR TITLE
Odt

### PR DESCRIPTION
**Pull request by Alex-Jordan**
Probably not for serious merge consideration. If you would like to idly browse code with your morning coffee, any XSLT observations you have are appreciated.

This is basic structures for an .odt file, and enough templates to get a worksheet with an introduction, some exercises, and `p` content. And everything that can go inside a `p` except math.

Thanks for the boost the other day about making math. I've hit an obstacle I am working on. Might start a discussion or wait until Friday. It feels like it may cause a significant delay, so I thought to get this much up for now.

### CODE REVIEW

**Comment by rbeezer** [comment]
That's looking good.  A real tour-de-force.  High-level organization and infrastructure looks solid.  Perhaps some more detail-oriented comments in a bit.

**Comment by rbeezer** [comment]
Some XSL discussion.  I miss starting a new conversion with a clean slate.  ;-)  No backward compatibility constraints or jitters.

* Some trailing whitespace about (its bright red in my `git diff`).  Otherwise use a regex in your editor to locate?
* Any reason to have the assembly stylesheet turned off?  It should not be a performance problem (its very fast).
* Is "Latin Modern" available by default?
* `boolean(parent::*/title or parent::statement/parent::*/title)` should be a boolean due to the "or" if you drop the `boolean`.  If you were only probing one path, you'd need it since you don't want the nodeset it would represent.  Try dropping these later when you can do before/after testing.
* `position()` can be very dangerous.  I hardly ever use it anymore, but it is tempting at first.  For example `boolean(*[not(&METADATA-FILTER;)][position() = 1][not(self::p)])`.  Not sure if `[1]` is still correct here.

**Comment by Alex-Jordan** [comment]
Thanks, I applied the more trivial edits.

> Any reason to have the assembly stylesheet turned off? It should not be a performance problem (its very fast).

I just haven't looked into understanding that part yet. Like, does it affect how I write the entry template?

> Is "Latin Modern" available by default?

Unsure. LibreOffice will default to something acceptable though if it cannot find a font. (With different defaults for paragraph text and header text.) No different than if an author with Latin Modern writes an ODT file using LibreOffice, then sends it to someone else who may not have Latin Modern.

> For example boolean(*[not(&METADATA-FILTER;)][position() = 1][not(self::p)]).

This is a construction where I need to know if the first child of something is a `p`. But not counting metadata children like `title`. So for example, if the element opens with a `sidebyside` instead of a `p`. A variant of this with `[1]` did not work, because `[not(&METADATA-FILTER;)][1]` is already an element, not a node set, so tacking on the `[not(self::p)]` didn't work. Any ideas?

**Comment by Alex-Jordan** [comment]
Closing this. I'm experiencing some issues with my laptop so I'm pushing all my work to GitHub just in case, including "temporary commits". So this is about to look like a mess.

**Pull request closed without merging**
