### PR TITLE
mbx for windows and notes in Author's Guide

### PR DESCRIPTION
**Pull request by daverosoff**
Rob,

I don't write a lot of Python, so I haven't tried to be idiomatic or match your style much. It should be quite obvious what is needed. I haven't done anything with the Sage sections, since I don't have access to the Windows 10 builds needed to run Sage in Windows. However, the `asy`, `tikz`, and `latex-image` components all succeed for format `svg` with test document AATA on my machine running Windows 7. Hope you approve of these changes.

Thanks,
Dave

### CODE REVIEW

**Comment by daverosoff** [comment]
The last two commits were a little clumsy on my part, sorry about that. I reworded and clarified throughout the two files, trying my best to keep all your revisions as well. The branch got away from me. Forgive me, I'm still working on internalizing the Principles<ellipsis />

**Comment by rbeezer** [comment]
Dear Dave,

I think I can unwind this - maybe.

* Is 9aa89c6a42a the first commit with new material?
* Please do not start a new pull request on a branch with already-merged stuff.  Pull from mainline and start a new branch.
* I do not know yet how to easily review a branch when it has merges from `dev` mixed in.  It'd be easier if you rebased your private branch before pushing it.
* If you make a pull request, you can add to that branch, especially if it is unlikely to cause any merge conflicts on my end.  But it'd be easier if you made a request and then left it alone for a couple days while I review it.

Other than building onto already-merged stuff, most of this is because of my own shortcomings on the review side, you've not done anything incorrectly.

Thanks for your help!  Together we'll get this sorted out. ;-)

Rob

**Comment by daverosoff** [comment]
Hi Rob,

Yes, the commit you mention is where I wanted this pull request to start. I didn't realize at the time how the history comes along with it. If you want, I can try to squash the commits together on my fork, or we can go from there. In the future I'll hold off on pull requests until I'm ready to stop working on something for a few days. 

Yesterday I reread some of GFA and now I know how to do a PR from a branch instead of from `dev`. Is this the right sequence?
* Pull from mainline MBX.
* Make changes on a branch.
* Pull from mainline into the branch.
* Rebase the branch onto dev.
* Do PR from the branch.

**Comment by rbeezer** [comment]
Just about!

In Step 3, instead: switch to `dev`, pull from mainline to update/extend `dev`, switch to your branch, then `rebase dev`  (I mentally insert "onto" in the middle of that last command).  You will resolve any conflicts locally as part of that rebase.   And you can do this repeatedly as you work and I am pushing changes.  

If a few days elapses before I review your PR, I will also rebase, which means you should not work on a branch that is being reviewed since I'll wreck the hashes on those commits eventually (even by just editing commit messages).  I imagine there may be a better way, I just do not know it.

Rob
Let me try the current PR later today and I'll scream for help if I need it.

**Comment by rbeezer** [comment]
I fetched all these commits into a fresh clone, built a new branch.

Then I started cherry-picking the "real" ons, one at a time onto a new branch.  First went well, the second had many conflicts that would take a while to figure out.

Can you save the affected files someplace safe, get a fresh clone, make a branch, copy save files onto existing and make sure you are not clobbering any edits I made from before, and make a new PR?  Or something?  Thanks.  Sorry for the trouble.

**Comment by daverosoff** [comment]
No problem, sorry to have botched it up. I fixed all those (or a similar group) of conflicts once so I don't blame you for not wanting to wade through them. I will do as you suggest though I may not get to it for a few days.

**Comment by rbeezer** [comment]
This is all merged on #322

**Pull request closed without merging**
