### PR TITLE
Extract asymptote addition

### PR DESCRIPTION
**Pull request by mdoob**
The ``extract-asymptote.xsl`` file  makes a last guess at determining 3D files with (essentially) a grep search for "import graph3;". Many 3D fiiles use "import three;" instead. An additional check for this case is added.

### CODE REVIEW

**Comment by mdoob** [comment]
Small change to recognize 3D files that use "import three;".

**Comment by rbeezer** [comment]
This pull request has four commits, and I was uncertain where the oldest ws rooted, since it is from an older pull request, and was changed in the process of merging it.  So I didn't think I could isolate it safely.

Instead, I just copied the new code into a new commit and referenced this pull request.

Thanks for the contribution!

**Comment by sean-fitzpatrick** [comment]
I haven't followed carefully (still in the middle of assigning grades and contacting cheaters) but if I understand the recent correspondence between John Bowman and us, we might not need the ability to detect 3D graphs: `asy -f svg -render=4` will produce decent SVG from any Asymptote file.

But it might come with the usual caveats about having up to date versions of everything.

**Comment by mdoob** [comment]
Yes, Sean, I think that is correct. The default value is render=-1,
so it has to be changed. The value render=4 is probably overkill
for most situations, but we could experiment.

As I surmised and John confirmed, older implementations will cause
problems. Should we throw a warning?

Cheers,
Michael

------------------------------------------------------------------
Michael Doob                    Telephone: (204) 474-9796
Department of Mathematics       email: Michael.Doob@UManitoba.ca
University of Manitoba
Winnipeg, MB, Canada R3T 2N2
------------------------------------------------------------------

________________________________________

**Comment by sean-fitzpatrick** [comment]
Yes -- I think Rob already added a warning that shows up if you run `mbx` with the `-v` option. We can edit it to give minimum version recommendations for `asy`, `dvigsm`, etc.

**Pull request closed without merging**
