### PR TITLE
Move WW sample chapter from PCC to AIM

### PR DESCRIPTION
**Pull request by Alex-Jordan**
Don't merge this (yet). But some testing and feedback would be appropriate and appreciated.

This moves the sample chapter to rely on AIM's -dev server instead of PCC's server. It required generalizing the mbx script some since it handles placement of temporary image files a little differently. Should be more robust now for a wider variety of server configurations. 

Test by making the sample-chapter-server-tex and the sample-chapter-latex PDF. I did this using both webwork.pcc.edu and webwork-dev.aimath.org, and the diff on the tex files was empty (except the time stamp).

Wait for merging. Two things still could be better. Once the -ptx server is caught up to -dev, this should use -ptx instead of -dev. And also even though -dev is on the develop branch of webwork, something is not right yet because the webwork extraction tool from the mbx script is not working. with the webwork-dev.aimath.org server. (It appears to work fine still with webwork.pcc.edu.)

### CODE REVIEW

**Comment by rbeezer** [comment]
I was going to ask if we could do this!  Third in line for pull requests, I'll test (**and not merge**) shortly.

**Comment by Alex-Jordan** [comment]
OK, now in addition to checking that everything is smooth with `make sample-chapter-server-tex`, you can also check that evreything is smooth with `make sample-chapter-extraction`. I get an empty diff with `make sample-chapter-server-tex`. 

With `make sample-chapter-extraction`, the .png files are different, but that is probably an internal timestamp or some other metadata about the image. (Actually, it may be that on the PCC server I turned off a border that the default distribution puts around these images.)

Then the diff is empty, except on the PCC server I have altered how fractions are printed. (The default distribution always wraps them in `\textstyle`, which I find irritating.) So there is a small diff, but it makes the output in line with how out-of-the-box webwork behaves.

This is still with the -dev server. I don't know if we should:

1. Move forward using -dev, and not even bother with -ptx until version 2.14 is released, at which point I would set up -ptx to be on 2.14 out of the box. And make a PR to switch references from -dev to -ptx. Or...

1. Set up -ptx this week on the develop branch of webwork. Then this PR could go ahead and switch -dev to -ptx. I'm not sure how I feel about setting up -ptx onto the develop branch of webwork though. I'm not 100% sure that 2.14 will capture everything that is currently merged into develop. So later when -ptx would move to version 2.14, there may be things to undo, especially in the configuration files that git does not track.

Option 1 is less work for me. So I guess I lean toward option 1. But I can be persuaded if option 2 is important.

**Comment by Alex-Jordan** [comment]
Oh I meant to mention: I _think_ David and Jeremy got the server/url issue sorted out, but no confirmation yet. But the behavior did change, and for right now, for me at least, it's working to produce static PTX output.

Another thing. From my home, extracting static PTX from the PCC server takes 15 seconds. From -dev, it takes 27 seconds. ORCCA takes around an hour using PCC, so with a bog project it could make a big difference. 

The webwork server can handle (within reason, and optimized through configuration variables) simultaneous requests, but the mbx script waits for each problem to finish before moving on to the next one. So there may be opportunity to speed things up on both ends. Not a job for this PR though.

**Comment by Alex-Jordan** [comment]
No one did anything to change the server/url behavior. But a theory to explain what was happening is that somewhere something was feeding me cached versions of the output. Maybe my browser (but I'm pretty sure I checked against that), maybe the server itself, or maybe within PCC's network.

The point is, go ahead and try (when you are back on duty). Still have the -dev versus -ptx question.

**Comment by rbeezer** [comment]
Chapter extraction fails.  Could be a local thing where I don't have the right libraries installed?

When I do `make sample-chapter-server-tex` I get several warnings per problem, but it does not fail.  Perhaps related.  Failure follows next.

```
MBX: sending webwork-48 to server to save in /tmp/ww/pdf/webwork-tex: origin is 'mbx'
/home/rob/.local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:789: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/home/rob/.local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:789: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/home/rob/.local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:789: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
```


For `make sample-chapter-extraction`:

```
rob@lava:~/mathbook/mathbook/examples/webwork$ make sample-chapter-extraction
install -d /tmp/ww/webwork-extraction
rm /tmp/ww/webwork-extraction/webwork-extraction.xml
/home/rob/mathbook/mathbook/script/mbx -v -c webwork -d /tmp/ww/webwork-extraction -s https://webwork-dev.aimath.org /home/rob/mathbook/mathbook/examples/webwork/sample-chapter/sample-chapter.xml
MBX: discovering MBX root directory from mbx script location
MBX: MBX distribution root directory: /home/rob/mathbook/mathbook
MBX: parsing configuration files: ['/home/rob/mathbook/mathbook/script/mbx.cfg', '/home/rob/mathbook/mathbook/user/mbx.cfg']
MBX: verifying directory: /tmp/ww/webwork-extraction
MBX: validating, cleaning server URL: https://webwork-dev.aimath.org
/home/rob/.local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:789: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/home/rob/.local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:789: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
MBX: writing representations of PTX-authored WeBWorK problem
MBX: sending function-with-domain-issues to server to save in /tmp/ww/webwork-extraction: origin is 'ptx'
Traceback (most recent call last):
  File "/home/rob/mathbook/mathbook/script/mbx", line 1458, in <module>
    webwork_to_xml(xslt_executable, mbx_xsl_dir, args.xml_file, args.server, output_dir)
  File "/home/rob/mathbook/mathbook/script/mbx", line 688, in webwork_to_xml
    raise ValueError(msg.format(wwurl, server_params) + root_cause)
ValueError: There was a problem collecting a problem,
 Server: https://webwork-dev.aimath.org/webwork2/html2xml
Request Parameters: (('answersSubmitted', '0'), ('displayMode', 'PTX'), ('courseID', 'anonymous'), ('userID', 'anonymous'), ('password', 'anonymous'), ('course_password', 'anonymous'), ('outputformat', 'ptx'), ('problemSource', 'RE9DVU1FTlQoKTsKbG9hZE1hY3JvcygiUEdzdGFuZGFyZC5wbCIsIk1hdGhPYmplY3RzLnBsIiwiUEdNTC5wbCIsIkFuc3dlckZvcm1hdEhlbHAucGwiLCJhbnN3ZXJIaW50cy5wbCIsIlBHY291cnNlLnBsIiwpO1RFWFQoYmVnaW5wcm9ibGVtKCkpO0NvbnRleHQoJ051bWVyaWMnKTskYSA9IHJhbmRvbSgyLDUsMSk7CiRhbnN3ZXIxID0gQ29tcHV0ZSgic3FydCh4LSRhKSIpOwokYW5zd2VyMS0+e2xpbWl0c30gPSBbJGErMSwkYSs0XTsKJGFuc3dlcjIgPSBDb21wdXRlKCJsbihhYnMoIHggLyAoeC0kYSkgKSkiKTsKJGFuc3dlcjItPnt0ZXN0X3BvaW50c30gPSBbWy01XSxbLTRdLFsxXSxbJGEtMV0sWzddLFs4XV07CiRhbnN3ZXIyZXZhbHVhdG9yID0gJGFuc3dlcjIgLT4gY21wKCkgLT4gd2l0aFBvc3RGaWx0ZXIoIEFuc3dlckhpbnRzKCBbQ29tcHV0ZSgibG4oYWJzKCh4LSRhKS94KSkiKSxdID0+ICJUaGlzIGlzIHRoZSBvcHBvc2l0ZSBvZiBjb3JyZWN0Li4uIiwpKTsKCkJFR0lOX1BHTUwKYS4gIFN1cHBvc2UgdGhlIGNvcnJlY3QgYW5zd2VyIGlzIFtgXGRpc3BsYXlzdHlsZSBbJGFuc3dlcjFdXHRleHR7Ln1gXQoKICAgICsgW19deyRhbnN3ZXIxfXt3aWR0aD0+MTV9CgoKCmEuICBTdXBwb3NlIHRoZSBjb3JyZWN0IGFuc3dlciBpcyBbYFxkaXNwbGF5c3R5bGUgWyRhbnN3ZXIyXVx0ZXh0ey59YF0KCiAgICArIFtfXXskYW5zd2VyMmV2YWx1YXRvcn17d2lkdGg9PjE1fQoKCgoKRU5EX1BHTUwKCkJFR0lOX1BHTUxfU09MVVRJT04KU29sdXRpb24gZXhwbGFuYXRpb24gZ29lcyBoZXJlLgoKCkVORF9QR01MX1NPTFVUSU9OCgpFTkRET0NVTUVOVCgpOw=='), ('problemSeed', '51'))
("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",)
Makefile:99: recipe for target 'sample-chapter-extraction' failed
make: *** [sample-chapter-extraction] Error 1
```

**Comment by rbeezer** [comment]
I think of the sample article (and all the samples) as "this is what a typical (non-developer) author will get right now" and it is consistent with documentation.  Of course for WW we need to assume an "up-to-date" server.  I think that means the latest stable/public version.  We can create whatever mayhem we want on -dev.  ;-)

So I'd propose the sample-chapter script points to  -ptx  and that server always has the latest version of WW.  We can switch the script up for testing, and maybe we make that an easy edit up high, or maybe we even make a side file with local choices.

**Comment by Alex-Jordan** [comment]
I just confirmed that I don't get this error when making the extraction from 62b2624. Do you see the same as this?:

```
syst203m4138:webwork alex.jordan$ pip show requests
---
Metadata-Version: 2.0
Name: requests
Version: 2.9.1
Summary: Python HTTP for Humans.
Home-page: http://python-requests.org
Author: Kenneth Reitz
Author-email: me@kennethreitz.com
Installer: pip
License: Apache 2.0
Location: /Library/Python/2.7/site-packages
Requires: 
Classifiers:
  Development Status :: 5 - Production/Stable
  Intended Audience :: Developers
  Natural Language :: English
  License :: OSI Approved :: Apache Software License
  Programming Language :: Python
  Programming Language :: Python :: 2.7
  Programming Language :: Python :: 3
  Programming Language :: Python :: 3.3
  Programming Language :: Python :: 3.4
  Programming Language :: Python :: 3.5
```

**Comment by Alex-Jordan** [comment]
WW 2.13 is the latest stable version, and does not produce PTX output. Version 2.14 will, whenever it is released. Right now, the develop branch will do this too.

So if what we are doing right now is to set up the sample chapter to use the new scheme, then it needs to be pointing to some ww server on the develop branch. That could be -dev, or -ptx if we temporarily make -ptx run on develop.

I'm unsure if I can get the new scheme completed, while still preserving the old scheme's functionality. Maybe.

**Comment by rbeezer** [comment]
```
Name: requests
Version: 2.10.0
Summary: Python HTTP for Humans.
Home-page: http://python-requests.org
Author: Kenneth Reitz
Author-email: me@kennethreitz.com
License: Apache 2.0
Location: /usr/lib/python3/dist-packages
Requires: 
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by rbeezer** [comment]
We are OK if things are not the way we want them long-term, in the short-term as we transition.

**Comment by Alex-Jordan** [comment]
OK, I leapfrogged you:
```
syst203m4138:webwork alex.jordan$ pip show requests
Name: requests
Version: 2.18.4
Summary: Python HTTP for Humans.
Home-page: http://python-requests.org
Author: Kenneth Reitz
Author-email: me@kennethreitz.org
License: Apache 2.0
Location: /Users/alex.jordan/Library/Python/2.7/lib/python/site-packages
Requires: urllib3, idna, chardet, certifi
Required-by: 
```
I still don't get an error from the `make sample-chapter-extraction`.


Just realized we have seen this before. On line 684, try changing `verify=True` to `verify=False`. It is already set to False back at line 343 for `make webwork-server-tex`. For some reason the verification succeeds for me, but not for you. IIRC that was the case with `make webwork-server-tex` as well. I guess it is not ideal to have `verify=False` but...

**Comment by Alex-Jordan** [comment]
Although I see my new version of requests requires something called `certifi`. Could be relevant.

**Comment by Alex-Jordan** [comment]
> We are OK if things are not the way we want them long-term, in the short-term as we transition.

Yeah but _which_ thing should be not the way we want it to be in the long term? The choices are to temporarily have -ptx use the develop branch. Or temporarily have the sample chapter direct people to use -dev.

I guess the right choice is to have -ptx temporarily use develop and hope there is nothing for anyone to notice one day when it reverts to 2.14. I just didn't want that answer because it means more work for me in the short term, as well as when the reversion will happen.

**Pull request closed without merging**
