### PR TITLE
Add support for an asymptote preamble

### PR DESCRIPTION
**Pull request by sean-fitzpatrick**
Added a short blurb in the guide, but didn't have time to touch the sample article

### CODE REVIEW

**Comment by rbeezer** [comment]
I don't have a newer `asy` executable, and I didn't even see a good item to move into a preamble for the sample article, so I just left that undone.

Moved out some trailing whitespace (my fault!) that your editor was fixing, onto a whitespace-only commit with my name to blame.

I use `<note>` for "Best Practices" - pretty major pieces of advice.  So I moved your note on colors/pens into the list of "Notes" just prior.

Thanks for putting this together.

**Comment by sean-fitzpatrick** [comment]
Ok, great! As far as I can tell there's no need to have xsl for this anywhere other than the Asymptote extraction template.
I suppose (for now) I've added a new schema violation but I'm all right with that :-)

**Comment by rbeezer** [comment]
Right.  I was going to add it to the schema but forgot.  Soon.

**Comment by rbeezer** [comment]
In the schema:  d8206fc749987c5a6c6b0e282897b811428db13e

**Comment by sean-fitzpatrick** [comment]
Awesome, thanks. Turns out asymptote segfaults on PDF output in Ubuntu 20.10. I've just set John Bowman up with ssh access to my laptop so he can try debugging. Workaround is to add `-render=0` to the executable but that might have unintended quality consequences. I'll let you know if we need to update the executable in the `pretext` script.

**Pull request closed without merging**
