### PR TITLE
Update windows-wsl.xml

### PR DESCRIPTION
**Pull request by mdoob**
A short introduction to installing and running pretext on Windows using the Windows Subsystem for Linux.

### CODE REVIEW

**Comment by kcrisman** [comment]
For reference, this might help with #569 .

**Comment by kcrisman** [comment]
I feel like a newbie might have trouble with "Open a PowerShell prompt as administrator and run:" and  "Open a command prompt" etc. if no experience with shell before.

**Comment by rbeezer** [comment]
Dear Michael,

Thanks for the contribution.  No laptop for next 2.5 weeks, so it'll be a bit until I can add this in.

Rob

**Comment by rbeezer** [comment]
Thanks very much, Michael.  This is a big help.  I did a bit of light editing of formatting, mostly pulling `aside` out of the insides of `p`, but no real content changes.  Website being updated now.

@kcrisman I'm not going to worry too much about providing comprehensive help on operating systems and other tools.  Folks should be able to find help elsewhere if some of these ideas are foreign.

**Pull request closed without merging**
